name: Super-Linter and Docker Image Push

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main

  push-docker-image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: super-lint  # Make sure to wait for the previous job to complete

    steps:
      - name: Login to Docker Hub
        run: docker login -u mdhussain284 -p Hussain@2844

      - name: Push Docker Image
        run: docker push mdhussain284/gitops:latest  # Replace with your image name

      - name: Logout from Docker Hub
        run: docker logout
